# properties 면 더 귀찮게 적음
spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
#    resources
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
#    url를 보고 설정해주기 때문에 안줘도 상관은 없을것이다 랬는데 안된다

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook
# 톰켓 포트 변경
server:
  port: 8090
#  기본적으로 80으로 날아감
